- type: entity
  id: StoriesBaseStationMaps
  abstract: true
  components:
    - type: MapSpawn
      groups:
        trade:
          paths:
          - /Maps/Stories/Misc/trading_outpost.yml
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          nameGrid: true

- type: entity
  id: StoriesBaseStationMapsWithPrison
  parent: StoriesBaseStationMaps
  abstract: true
  components:
    - type: MapSpawn
      groups:
        prison:
          paths:
          - /Maps/Stories/Misc/prison.yml
        trade:
          paths:
          - /Maps/Stories/Misc/trading_outpost.yml

- type: entity
  id: StoriesBaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Stories/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        mining:
          paths:
          - /Maps/Stories/Shuttles/mining.yml
        # Spawn last
        ruins:
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/relaystation.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml

- type: entity
  id: StoriesBaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm
      map: /Maps/Stories/centcomm.yml

