- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAspid
  - StoriesBagel
  - StoriesBarratry
  - StoriesCluster
  - StoriesCore
  - StoriesOmega
  - StoriesPacked
  - StoriesMarathon
  - StoriesAtlas
#  - StoriesEuropa
  - StoriesMeta
  - StoriesOrigin
  - StoriesSaltern

  - StoriesAvrite
  - StoriesDelta
  - StoriesGate
  - StoriesOutpost
  - StoriesSpectrum
  - StoriesSilly

# Space Prison Maps
  - StoriesBox
  - StoriesFland
  - StoriesKettle

# New Maps
  - StoriesReach
  - StoriesGemini
